// this file is intended to be used in a few of the GitHub Actions workflows to take
// output generated by the Actions and then write it to a file so a PR can be created,
// rather than creating an issue

const { rename } = require('node:fs/promises')
const { resolve, basename, extname } = require('node:path');
const { DateTime } = require('luxon')

// sourceFile should be a filename that we want to rename and move
// outputLocation should be a path to where we want the renamed file to end up
async function convertToFileWithDate (sourceFile, outputLocation, prefix) {
  try {
    // get the usable path for our source file
    const resolvedSource = resolve(sourceFile)

    // get the usable path for our output location
    const resolvedOutputLocation = resolve(outputLocation)

    // build out our usable date for the output filename
    const now = DateTime.now()
    const usableDate = now.toISODate()

    // build out the filename for our output file
    const resolvedOutput = `${resolvedOutputLocation}/${prefix}-${usableDate}.${extname(resolvedSource).slice(1)}`

    // rename the file from the original name and location to the new name and location
    await rename(resolvedSource, resolvedOutput)
  } catch (err) {
    console.error(err.message)
  }
}

module.exports = convertToFileWithDate