name: Stale Repo Watchtower (Twilio)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  build:
    name: Stale Repo Watchtower
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run stale-repos Tool
      uses: github/stale-repos@v1
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ORGANIZATION: twilio
        INACTIVE_DAYS: 182
        ACTIVITY_METHOD: "pushed"
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
    - name: Update npm
      run: npm install -g npm
    - name: Install Dependencies
      run: npm install
    - name: Move Watchtower Report File to Storage
      run: npm run convert:watchtower:twilio
    - name: Run gr2m/create-or-update-pull-request
      uses: gr2m/create-or-update-pull-request-action@v1 # Create a PR or update the Action's existing PR
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body: >
          Monthly Watchtower report, automatically generated with GitHub Actions.
        branch: actions/watchtower  # Custom branch *just* for this Action.
        commit-message: 'doc: generate watchtower report'
        title: 'doc: generate watchtower report'
        assignees: bnb # change to whoever you want to be assigned to this PR
        auto-merge: squash